// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Postly.Api.Persistence;

#nullable disable

namespace Postly.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Postly.Api.Persistence.Entities.Follow", b =>
                {
                    b.Property<long>("FollowerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FollowedId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("FollowerId", "FollowedId");

                    b.HasIndex("FollowedId");

                    b.HasIndex("FollowerId");

                    b.ToTable("Follows", (string)null);
                });

            modelBuilder.Entity("Postly.Api.Persistence.Entities.Like", b =>
                {
                    b.Property<long>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserAccountId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("Likes", (string)null);
                });

            modelBuilder.Entity("Postly.Api.Persistence.Entities.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EditedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReplyToPostId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc", "Id")
                        .IsDescending();

                    b.HasIndex("AuthorId", "CreatedAtUtc", "Id")
                        .IsDescending(false, true, true);

                    b.HasIndex("ReplyToPostId", "CreatedAtUtc", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("Postly.Api.Persistence.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserAccountId", "ExpiresAtUtc");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("Postly.Api.Persistence.Entities.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("AvatarBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("AvatarContentType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AvatarUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("UserAccounts", (string)null);
                });

            modelBuilder.Entity("Postly.Api.Persistence.Entities.Follow", b =>
                {
                    b.HasOne("Postly.Api.Persistence.Entities.UserAccount", "Followed")
                        .WithMany("Followers")
                        .HasForeignKey("FollowedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Postly.Api.Persistence.Entities.UserAccount", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Followed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("Postly.Api.Persistence.Entities.Like", b =>
                {
                    b.HasOne("Postly.Api.Persistence.Entities.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Postly.Api.Persistence.Entities.UserAccount", "UserAccount")
                        .WithMany("Likes")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Postly.Api.Persistence.Entities.Post", b =>
                {
                    b.HasOne("Postly.Api.Persistence.Entities.UserAccount", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Postly.Api.Persistence.Entities.Session", b =>
                {
                    b.HasOne("Postly.Api.Persistence.Entities.UserAccount", "UserAccount")
                        .WithMany("Sessions")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Postly.Api.Persistence.Entities.Post", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("Postly.Api.Persistence.Entities.UserAccount", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("Likes");

                    b.Navigation("Posts");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
